/**
 * lib/youtube/client.ts
 * MealOS AI — YouTube Data API v3 client (ISSUE-131)
 *
 * Wraps search.list + videos.list to resolve one recipe video per query:
 * given a recipe name (and optional cuisine), returns the single best match
 * as a YouTubeRecipeResult, or a typed Degraded result — NEVER throws.
 *
 * Contract (docs/AGENTS.md §4.1 + ISSUE-131 AC):
 *   - Query: "{recipeName} {cuisine} recipe", type=video, videoDuration=medium
 *   - Top result only; zero matches → Degraded NO_RESULTS (not an error path
 *     downstream: the Tool Agent settles NO_RESULTS to youtube: null)
 *   - Quota exhaustion (403 quotaExceeded family) → QUOTA_EXCEEDED
 *   - Any other failure (5xx, network, malformed body, timeout) → API_DOWN
 *   - Timeout 2000ms total (Tool Agent per-tool budget for youtube)
 *   - API key from env.YOUTUBE_API_KEY (lib/env throws at boot when missing)
 *
 * Import restriction (rule N10): this module may only be imported from
 * lib/agents/tool.ts — the Tool Agent is the sole external intermediary.
 * Enforced by the no-restricted-imports ESLint rule.
 *
 * keyTimestamps is always [] here: step timestamps are generated by the
 * Planning Agent during recipe-step generation (ISSUE-141), not fetched.
 */

import { env } from '@/lib/env'
import type { YouTubeRecipeResult, YouTubeToolErrorCode } from '@/types/swiggy'
import type { YouTubeVideoId, Seconds, ISODateTime } from '@/types/primitives'

// ── Local result shapes (structurally compatible with lib/mcp/mock) ──────────
// lib/mcp/* is import-restricted to lib/agents/tool.ts, so the Degraded shape
// is declared locally; TypeScript's structural typing keeps the two in sync
// with the ToolResult<T> contract the Tool Agent consumes.

export interface YouTubeDegraded {
  available: false
  errorCode: YouTubeToolErrorCode
  message: string
}

export type YouTubeSearchResult = YouTubeRecipeResult | YouTubeDegraded

export interface SearchRecipeParams {
  recipeName: string
  cuisine?: string
  style?: 'quick' | 'detailed' | 'beginner' | 'restaurant-style'
  maxDurationMinutes?: number
}

/** Minimal fetch surface — lets tests inject a fake without a full Response. */
export type FetchLike = (
  url: string,
  init?: { signal?: AbortSignal },
) => Promise<{ ok: boolean; status: number; json(): Promise<unknown> }>

export interface YouTubeClientDeps {
  /** Defaults to env.YOUTUBE_API_KEY (validated at boot). */
  apiKey?: string
  /** Defaults to globalThis.fetch. */
  fetchFn?: FetchLike
  /** Total request budget in ms; default 2000 (AGENTS.md §4.1). */
  timeoutMs?: number
}

// ── API response shapes (only the fields we read) ────────────────────────────

interface SearchListResponse {
  items?: {
    id?: { videoId?: string }
    snippet?: {
      title?: string
      channelTitle?: string
      publishedAt?: string
      thumbnails?: Record<string, { url?: string } | undefined>
    }
  }[]
}

interface VideosListResponse {
  items?: {
    contentDetails?: { duration?: string }
    statistics?: { viewCount?: string }
  }[]
}

interface ApiErrorBody {
  error?: { errors?: { reason?: string }[] }
}

// ── ISO 8601 duration parsing ────────────────────────────────────────────────

const ISO_DURATION = /^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/

/**
 * Parse an ISO 8601 duration (YouTube contentDetails.duration, e.g. "PT12M34S")
 * into whole seconds. Unparseable input returns 0.
 */
export function parseIso8601Duration(iso: string): number {
  const match = ISO_DURATION.exec(iso)
  if (!match) return 0
  const [, h, m, s] = match
  return Number(h ?? 0) * 3600 + Number(m ?? 0) * 60 + Number(s ?? 0)
}

// ── Error classification ─────────────────────────────────────────────────────

const QUOTA_REASONS = new Set(['quotaExceeded', 'dailyLimitExceeded', 'rateLimitExceeded'])

function degraded(errorCode: YouTubeToolErrorCode, message: string): YouTubeDegraded {
  return { available: false, errorCode, message }
}

// ── Client ────────────────────────────────────────────────────────────────────

const API_BASE = 'https://www.googleapis.com/youtube/v3'
const DEFAULT_TIMEOUT_MS = 2000

export class YouTubeDataClient {
  private readonly apiKey: string
  private readonly fetchFn: FetchLike
  private readonly timeoutMs: number

  constructor(deps: YouTubeClientDeps = {}) {
    this.apiKey = deps.apiKey ?? env.YOUTUBE_API_KEY
    this.fetchFn = deps.fetchFn ?? (globalThis.fetch as FetchLike)
    this.timeoutMs = deps.timeoutMs ?? DEFAULT_TIMEOUT_MS
  }

  /**
   * Find the single best recipe video for a recipe name (+ optional cuisine).
   * Conforms to the Tool Agent's injectable YouTubeClient boundary.
   */
  async searchRecipe(params: SearchRecipeParams): Promise<YouTubeSearchResult> {
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), this.timeoutMs)
    try {
      return await this.doSearch(params, controller.signal)
    } catch (err) {
      return classifyThrown(err)
    } finally {
      clearTimeout(timer)
    }
  }

  private async doSearch(
    params: SearchRecipeParams,
    signal: AbortSignal,
  ): Promise<YouTubeSearchResult> {
    const query = [params.recipeName, params.cuisine, 'recipe'].filter(Boolean).join(' ')

    const searchUrl = new URL(`${API_BASE}/search`)
    searchUrl.searchParams.set('part', 'snippet')
    searchUrl.searchParams.set('type', 'video')
    searchUrl.searchParams.set('videoDuration', 'medium')
    searchUrl.searchParams.set('maxResults', '1')
    searchUrl.searchParams.set('q', query)
    searchUrl.searchParams.set('key', this.apiKey)

    const searchRes = await this.fetchFn(searchUrl.toString(), { signal })
    if (!searchRes.ok) return await classifyHttpFailure(searchRes)

    const search = (await searchRes.json()) as SearchListResponse
    const top = search.items?.[0]
    const videoId = top?.id?.videoId
    if (!top || !videoId) {
      return degraded('NO_RESULTS', `No YouTube video found for "${query}"`)
    }

    const videosUrl = new URL(`${API_BASE}/videos`)
    videosUrl.searchParams.set('part', 'contentDetails,statistics')
    videosUrl.searchParams.set('id', videoId)
    videosUrl.searchParams.set('key', this.apiKey)

    const videosRes = await this.fetchFn(videosUrl.toString(), { signal })
    if (!videosRes.ok) return await classifyHttpFailure(videosRes)

    const videos = (await videosRes.json()) as VideosListResponse
    const detail = videos.items?.[0]
    if (!detail) {
      return degraded('NO_RESULTS', `Video ${videoId} has no retrievable details`)
    }

    return {
      videoId: videoId as YouTubeVideoId,
      title: top.snippet?.title ?? '',
      channelName: top.snippet?.channelTitle ?? '',
      durationSeconds: parseIso8601Duration(detail.contentDetails?.duration ?? '') as Seconds,
      thumbnailUrl:
        top.snippet?.thumbnails?.['high']?.url ?? top.snippet?.thumbnails?.['default']?.url ?? '',
      viewCount: Number(detail.statistics?.viewCount ?? 0),
      publishedAt: (top.snippet?.publishedAt ?? '') as ISODateTime,
      keyTimestamps: [],
    }
  }
}

/** Map a non-ok HTTP response to the typed degraded taxonomy. */
async function classifyHttpFailure(res: {
  status: number
  json(): Promise<unknown>
}): Promise<YouTubeDegraded> {
  if (res.status === 403) {
    const body = (await res.json().catch(() => ({}))) as ApiErrorBody
    const reason = body.error?.errors?.[0]?.reason ?? ''
    if (QUOTA_REASONS.has(reason)) {
      return degraded('QUOTA_EXCEEDED', 'YouTube API quota exhausted')
    }
  }
  return degraded('API_DOWN', `YouTube API request failed with status ${res.status}`)
}

/** Thrown errors (network, abort/timeout, malformed JSON) collapse to API_DOWN. */
function classifyThrown(err: unknown): YouTubeDegraded {
  const message = err instanceof Error ? err.message : String(err)
  return degraded('API_DOWN', `YouTube API unreachable: ${message}`)
}
