/**
 * lib/cooking/pantry.ts
 * MealOS AI — Pantry gap check (ISSUE-134)
 *
 * Compares a recipe's ingredient list against the user's stored pantry
 * ('pantry.staples' fact) and splits it into have / missing. The missing
 * list feeds the Instamart cart CTA (ISSUE-135).
 *
 * Matching is case-insensitive and partial in both directions so label
 * variations resolve: recipe "Basmati Rice" matches pantry "basmati rice 1kg",
 * and pantry "rice" matches recipe "basmati rice".
 *
 * NEVER throws: an absent, empty, or corrupt pantry — or a failed fact
 * read — degrades to "everything is missing", which is always a safe
 * answer for a shopping-cart suggestion.
 */

import { getFactByKey } from '@/lib/repositories/memoryFactRepo'
import { FACT_KEYS } from '@/lib/memory/factKeys'

export interface PantryGapResult {
  /** Recipe ingredients present in the pantry, original casing preserved. */
  have: string[]
  /** Recipe ingredients absent from the pantry, original casing preserved. */
  missing: string[]
}

const PANTRY_KEY = FACT_KEYS.find((k) => k.startsWith('pantry.')) ?? 'pantry.staples'

function normalize(label: string): string {
  return label.trim().toLowerCase()
}

/** True when either normalized label contains the other. */
function labelsMatch(ingredient: string, pantryEntry: string): boolean {
  return pantryEntry.includes(ingredient) || ingredient.includes(pantryEntry)
}

/**
 * Split a recipe's ingredients into have/missing against the user's pantry.
 *
 * @param recipeIngredients - Ingredient names as generated by the Planning Agent
 * @param userId - Internal user UUID (not Clerk ID)
 */
export async function checkPantryGaps(
  recipeIngredients: string[],
  userId: string,
): Promise<PantryGapResult> {
  let pantry: string[] = []
  try {
    const fact = await getFactByKey(userId, PANTRY_KEY)
    if (fact && Array.isArray(fact.factValue)) {
      pantry = fact.factValue.filter((v): v is string => typeof v === 'string').map(normalize)
    }
  } catch {
    // Failed read degrades to an empty pantry — all ingredients missing.
  }

  const have: string[] = []
  const missing: string[] = []
  for (const ingredient of recipeIngredients) {
    const normalized = normalize(ingredient)
    if (pantry.some((entry) => labelsMatch(normalized, entry))) {
      have.push(ingredient)
    } else {
      missing.push(ingredient)
    }
  }
  return { have, missing }
}
